services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
